"""add messages table

Revision ID: 409f1130cf97
Revises: dad4f170c40a
Create Date: 2023-11-24 23:45:05.501780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409f1130cf97'
down_revision = 'dad4f170c40a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('message_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###
